### ISSUE TITLE
Cannot find module 'optparse'

### ISSUE THREAD

**Issue by gradus** [gradus/coffeecup#2]
Need to make the coffeecup bin work without the following error unless optparse is installed globally.

$ coffeecup -h

Error: Cannot find module 'optparse'
    at Function._resolveFilename (module.js:332:11)
    at Function._load (module.js:279:25)
    at Module.require (module.js:354:17)
    at require (module.js:370:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/coffeecup/bin/coffeecup:12:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/coffeecup/bin/coffeecup:110:4)
    at Module._compile (module.js:441:26)
    at Object.run (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/coffee-script.js:68:25)
    at /usr/local/lib/node_modules/coffee-script/lib/coffee-script/command.js:135:29
    at /usr/local/lib/node_modules/coffee-script/lib/coffee-script/command.js:110:18

**Comment by gradus** [comment]
Latest version seems to fix this issue
