### ISSUE TITLE
Cannot find module 'uglify-js'

### ISSUE THREAD

**Issue by gradus** [gradus/coffeecup#3]
unless uglify-js is installed globally following error occurs when running 'cake test'

Error: Cannot find module 'uglify-js'
    at Function._resolveFilename (module.js:332:11)
    at Function._load (module.js:279:25)
    at Module.require (module.js:354:17)
    at require (module.js:370:17)
    at Object.<anonymous> (/Users/klop/node/coffeecup/src/compiler.coffee:7:10)
    at Object.<anonymous> (/Users/klop/node/coffeecup/src/compiler.coffee:286:4)
    at Module._compile (module.js:441:26)
    at Object..coffee (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/coffee-script.js:21:21)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)

**Comment by gradus** [comment]
latest release fixes this issue
