### ISSUE TITLE
Express 3.1: TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by sokoloveg** [gradus/coffeecup#60]
node 0.8.20
express 3.1.0
coffeecup 0.3.19
All install from npm.

cd node_modules/coffeecup/examples/express/
coffee app.coffee

When trying to open http://localhost:3000/ error appears:

TypeError: Cannot read property '0' of undefined
    at new View (/home/neos/node_modules/express/lib/view.js:41:65)
    at Function.app.render (/home/neos/node_modules/express/lib/application.js:486:12)
    at ServerResponse.res.render (/home/neos/node_modules/express/lib/response.js:753:7)
    at app.get.res.render.foo (/home/neos/node_modules/coffeecup/examples/express/app.coffee:11:16)
    at callbacks (/home/neos/node_modules/express/lib/router/index.js:161:37)
    at param (/home/neos/node_modules/express/lib/router/index.js:135:11)
    at pass (/home/neos/node_modules/express/lib/router/index.js:142:5)
    at Router._dispatch (/home/neos/node_modules/express/lib/router/index.js:170:5)
    at Object.router (/home/neos/node_modules/express/lib/router/index.js:33:10)
    at next (/home/neos/node_modules/express/node_modules/connect/lib/proto.js:199:15)

**Comment by gradus** [comment]
Fixed Express example.  thanks.

**Comment by symis84** [comment]
Fixed where?
tks

**Comment by gradus** [comment]
in examples/express/views/index.coffee removed partial
commit 09ba991974973dc2b5f9a822535964991097259d
