### ISSUE TITLE
Express 3.1: ReferenceError: partial is not defined

### ISSUE THREAD

**Issue by sokoloveg** [gradus/coffeecup#61]
node 0.8.20
express 3.1.0 (from npm)
coffeecup 0.3.19 (from github)

cd node_modules/coffeecup/examples/express/
coffee app.coffee

When trying to open http://localhost:3000/ error appears:

ReferenceError: partial is not defined
    at Object.eval (eval at <anonymous> (/home/neos/node_modules/coffeecup/lib/coffeecup.js:410:10))
    at eval (eval at <anonymous> (/home/neos/node_modules/coffeecup/lib/coffeecup.js:410:10))
    at coffeecup.__express.render (/home/neos/node_modules/coffeecup/lib/coffeecup.js:458:25)
    at coffeecup.__express (/home/neos/node_modules/coffeecup/lib/coffeecup.js:479:16)
    at fs.readFile (fs.js:176:14)
    at Object.oncomplete (fs.js:297:15)

Examples "/login" and "/inline" work fine.

**Comment by gradus** [comment]
res.partial() and partial() (within templates) have been removed in express 3.x
removing line 12 in index.coffee in the express example will get rid of this error.  If anyone has a non hacky way to address partials with express 3.x and coffeecup I would love to hear it.
