### ISSUE TITLE
If I use the HTML5 main tag I get errors

### ISSUE THREAD

**Issue by greduan** [gradus/coffeecup#74]
@gradus 
If I use `main '.some-class'` or something along these lines I get:

```
error: An error occured: 
ReferenceError: main is not defined
    at Object.eval (eval at <anonymous> (/srv/http/docpad/node_modules/docpad-plugin-coffeekup/node_modules/coffeecup/lib/coffeecup.js:411:10), <anonymous>:326:9)
    at Object.__cc.render_contents (eval at <anonymous> (/srv/http/docpad/node_modules/docpad-plugin-coffeekup/node_modules/coffeecup/lib/coffeecup.js:411:10), <anonymous>:108:29)
    at Object.__cc.render_tag (eval at <anonymous> (/srv/http/docpad/node_modules/docpad-plugin-coffeekup/node_modules/coffeecup/lib/coffeecup.js:411:10), <anonymous>:139:14)
    at Object.tag (eval at <anonymous> (/srv/http/docpad/node_modules/docpad-plugin-coffeekup/node_modules/coffeecup/lib/coffeecup.js:411:10), <anonymous>:189:17)
    at Object.__cc.tag (eval at <anonymous> (/srv/http/docpad/node_modules/docpad-plugin-coffeekup/node_modules/coffeecup/lib/coffeecup.js:411:10), <anonymous>:38:18)
    at div (eval at <anonymous> (/srv/http/docpad/node_modules/docpad-plugin-coffeekup/node_modules/coffeecup/lib/coffeecup.js:411:10), <anonymous>:2:328)
    at Object.eval (eval at <anonymous> (/srv/http/docpad/node_modules/docpad-plugin-coffeekup/node_modules/coffeecup/lib/coffeecup.js:411:10), <anonymous>:324:14)
    at Object.__cc.render_contents (eval at <anonymous> (/srv/http/docpad/node_modules/docpad-plugin-coffeekup/node_modules/coffeecup/lib/coffeecup.js:411:10), <anonymous>:108:29)
    at Object.__cc.render_tag (eval at <anonymous> (/srv/http/docpad/node_modules/docpad-plugin-coffeekup/node_modules/coffeecup/lib/coffeecup.js:411:10), <anonymous>:139:14)
    at Object.tag (eval at <anonymous> (/srv/http/docpad/node_modules/docpad-plugin-coffeekup/node_modules/coffeecup/lib/coffeecup.js:411:10), <anonymous>:189:17)
    at Object.__cc.tag (eval at <anonymous> (/srv/http/docpad/node_modules/docpad-plugin-coffeekup/node_modules/coffeecup/lib/coffeecup.js:411:10), <anonymous>:38:18)
    at div (eval at <anonymous> (/srv/http/docpad/node_modules/docpad-plugin-coffeekup/node_modules/coffeecup/lib/coffeecup.js:411:10), <anonymous>:2:328)
    at Object.eval (eval at <anonymous> (/srv/http/docpad/node_modules/docpad-plugin-coffeekup/node_modules/coffeecup/lib/coffeecup.js:411:10), <anonymous>:320:5)
    at Object.__cc.render_contents (eval at <anonymous> (/srv/http/docpad/node_modules/docpad-plugin-coffeekup/node_modules/coffeecup/lib/coffeecup.js:411:10), <anonymous>:108:29)
    at Object.__cc.render_tag (eval at <anonymous> (/srv/http/docpad/node_modules/docpad-plugin-coffeekup/node_modules/coffeecup/lib/coffeecup.js:411:10), <anonymous>:139:14)
    at Object.tag (eval at <anonymous> (/srv/http/docpad/node_modules/docpad-plugin-coffeekup/node_modules/coffeecup/lib/coffeecup.js:411:10), <anonymous>:189:17)
    at Object.__cc.tag (eval at <anonymous> (/srv/http/docpad/node_modules/docpad-plugin-coffeekup/node_modules/coffeecup/lib/coffeecup.js:411:10), <anonymous>:38:18)
    at body (eval at <anonymous> (/srv/http/docpad/node_modules/docpad-plugin-coffeekup/node_modules/coffeecup/lib/coffeecup.js:411:10), <anonymous>:2:274)
    at Object.eval (eval at <anonymous> (/srv/http/docpad/node_modules/docpad-plugin-coffeekup/node_modules/coffeecup/lib/coffeecup.js:411:10), <anonymous>:319:10)
    at Object.__cc.render_contents (eval at <anonymous> (/srv/http/docpad/node_modules/docpad-plugin-coffeekup/node_modules/coffeecup/lib/coffeecup.js:411:10), <anonymous>:108:29)
    at Object.__cc.render_tag (eval at <anonymous> (/srv/http/docpad/node_modules/docpad-plugin-coffeekup/node_modules/coffeecup/lib/coffeecup.js:411:10), <anonymous>:139:14)
    at Object.tag (eval at <anonymous> (/srv/http/docpad/node_modules/docpad-plugin-coffeekup/node_modules/coffeecup/lib/coffeecup.js:411:10), <anonymous>:189:17)
    at Object.__cc.tag (eval at <anonymous> (/srv/http/docpad/node_modules/docpad-plugin-coffeekup/node_modules/coffeecup/lib/coffeecup.js:411:10), <anonymous>:38:18)
    at html (eval at <anonymous> (/srv/http/docpad/node_modules/docpad-plugin-coffeekup/node_modules/coffeecup/lib/coffeecup.js:411:10), <anonymous>:2:657)
    at Object.eval (eval at <anonymous> (/srv/http/docpad/node_modules/docpad-plugin-coffeekup/node_modules/coffeecup/lib/coffeecup.js:411:10), <anonymous>:269:1)
    at eval (eval at <anonymous> (/srv/http/docpad/node_modules/docpad-plugin-coffeekup/node_modules/coffeecup/lib/coffeecup.js:411:10), <anonymous>:345:4)
    at Object.coffeecup.render (/srv/http/docpad/node_modules/docpad-plugin-coffeekup/node_modules/coffeecup/lib/coffeecup.js:444:10)
    at CoffeekupPlugin.renderCoffeeKup (/srv/http/docpad/node_modules/docpad-plugin-coffeekup/out/coffeekup.plugin.js:37:25)
    at CoffeekupPlugin.render (/srv/http/docpad/node_modules/docpad-plugin-coffeekup/out/coffeekup.plugin.js:46:21)
    at ambi (/usr/lib/node_modules/docpad/node_modules/ambi/out/lib/ambi.js:21:27)
    at Task.<anonymous> (/usr/lib/node_modules/docpad/node_modules/bal-util/out/lib/events.js:39:16)
    at ambi (/usr/lib/node_modules/docpad/node_modules/ambi/out/lib/ambi.js:21:27)
    at /usr/lib/node_modules/docpad/node_modules/taskgroup/out/lib/taskgroup.js:82:19
    at process._tickDomainCallback (node.js:459:13)
```

Notice I am using DocPad and using the [coffeekup plugin](https://github.com/docpad/docpad-plugin-coffeekup).
Might want to look into this?

I posted it on the plugin's and it seems it's a plugin on this side. here's the issue of the plugin: https://github.com/docpad/docpad-plugin-coffeekup/issues/1

**Comment by gradus** [comment]
thanks @Greduan I have added support for the html5 `main` element

**Comment by gradus** [comment]
note:  if you run across an element that is not supported in coffeecup, you can always use `tag 'element'`
obviously `var` is out, so you would have to use `tag 'var'`
in the case of the `main` tag, you could have used `tag 'main'`

**Comment by greduan** [comment]
@gradus Excellent thanks! Nice tip, will keep it in mind. :)
